#!/usr/bin/env python3
"""Build the public operation registry from the canonical OpenAPI document."""

import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / "openapi" / "replynodes-fetcher.openapi.json"
DEST = ROOT / "lib" / "replynodes" / "operation_registry.rb"


def snake(value):
    value = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", value)
    return value.replace("-", "_").lower()


def camel(value):
    return "".join(part[:1].upper() + part[1:] for part in re.split(r"(?=[A-Z])", value) if part)


def ruby_literal(value):
    return json.dumps(value, ensure_ascii=False)


document = json.loads(SPEC.read_text())
operations = []
for path, path_item in document["paths"].items():
    operation = path_item.get("get")
    if operation is None:
        continue
    params = []
    for parameter in operation.get("parameters", []):
        name = parameter["name"]
        params.append(
            {
                "name": snake(name),
                "wire_name": name,
                "location": parameter["in"],
                "required": parameter.get("required", False),
            }
        )
    tag = operation["tags"][0]
    operation_name = snake(operation["operationId"])
    operations.append(
        {
            "name": operation_name,
            "operation_id": operation["operationId"],
            "path": path,
            "api_class": f"{camel(tag)}Api",
            "generated_method": operation_name,
            "parameters": params,
        }
    )

operations.sort(key=lambda item: item["name"])
lines = [
    "# frozen_string_literal: true",
    "",
    "# This file is generated by scripts/generate_registry.py from the canonical",
    "# ReplyNodes Fetcher OpenAPI contract. Do not hand-edit it.",
    "module ReplyNodes",
    "  OPERATIONS = {",
]
for operation in operations:
    lines.append(f"    {operation['name']}: {{")
    lines.append(f"      operation_id: {ruby_literal(operation['operation_id'])},")
    lines.append(f"      path: {ruby_literal(operation['path'])},")
    lines.append(f"      api_class: {ruby_literal(operation['api_class'])},")
    lines.append(f"      generated_method: :{operation['generated_method']},")
    lines.append("      parameters: [")
    for parameter in operation["parameters"]:
        required = "true" if parameter["required"] else "false"
        lines.append(
            "        { name: :%s, wire_name: %s, location: :%s, required: %s },"
            % (
                parameter["name"],
                ruby_literal(parameter["wire_name"]),
                parameter["location"],
                required,
            )
        )
    lines.append("      ].freeze")
    lines.append("    }.freeze,")
lines.extend([
    "  }.freeze",
    "  ALIASES = {}.freeze",
    "end",
    "",
])
DEST.write_text("\n".join(lines))
