=begin
#ReplyNodes Fetcher API

#SDK contract for ReplyNodes public, read-only data operations. Every SDK operation is an authenticated HTTP GET.

The version of the OpenAPI document: v1

Generated by: https://openapi-generator.tech
Generator version: 7.10.0

=end

# Common files
require 'replynodes/api_client'
require 'replynodes/api_error'
require 'replynodes/version'
require 'replynodes/configuration'

# Models
require 'replynodes/models/brand_fonts_data'
require 'replynodes/models/brand_fonts_response'
require 'replynodes/models/credit_topup_required'
require 'replynodes/models/error_detail'
require 'replynodes/models/error_response'
require 'replynodes/models/pagination'
require 'replynodes/models/payment_required'
require 'replynodes/models/payment_required_accountless_extensions'
require 'replynodes/models/payment_required_accountless_extensions_x_replynodes_accountless'
require 'replynodes/models/payment_required_extensions'
require 'replynodes/models/payment_required_prepaid_extensions'
require 'replynodes/models/payment_required_prepaid_extensions_topup'
require 'replynodes/models/payment_required_resource'
require 'replynodes/models/payment_required_response'
require 'replynodes/models/payment_requirements'
require 'replynodes/models/response_meta'
require 'replynodes/models/success_response'

# APIs
require 'replynodes/api/app_store_api'
require 'replynodes/api/brand_api'
require 'replynodes/api/fomo_api'
require 'replynodes/api/google_api'
require 'replynodes/api/google_maps_api'
require 'replynodes/api/google_play_api'
require 'replynodes/api/google_shopping_api'
require 'replynodes/api/hacker_news_api'
require 'replynodes/api/instagram_api'
require 'replynodes/api/reddit_api'
require 'replynodes/api/tiktok_api'
require 'replynodes/api/web_api'
require 'replynodes/api/youtube_api'

module ReplyNodesGenerated
  class << self
    # Customize default settings for the SDK using block.
    #   ReplyNodesGenerated.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
