# frozen_string_literal: true

# This file is generated by scripts/generate_registry.py from the canonical
# ReplyNodes Fetcher OpenAPI contract. Do not hand-edit it.
module ReplyNodes
  OPERATIONS = {
    app_store_app: {
      operation_id: "appStoreApp",
      path: "/v1/appstore/app",
      api_class: "AppStoreApi",
      generated_method: :app_store_app,
      parameters: [
        { name: :id, wire_name: "id", location: :query, required: false },
        { name: :app_id, wire_name: "appId", location: :query, required: false },
        { name: :country, wire_name: "country", location: :query, required: false },
        { name: :lang, wire_name: "lang", location: :query, required: false },
        { name: :ratings, wire_name: "ratings", location: :query, required: false },
      ].freeze
    }.freeze,
    app_store_developer: {
      operation_id: "appStoreDeveloper",
      path: "/v1/appstore/developer",
      api_class: "AppStoreApi",
      generated_method: :app_store_developer,
      parameters: [
        { name: :dev_id, wire_name: "devId", location: :query, required: true },
        { name: :country, wire_name: "country", location: :query, required: false },
        { name: :lang, wire_name: "lang", location: :query, required: false },
      ].freeze
    }.freeze,
    app_store_list: {
      operation_id: "appStoreList",
      path: "/v1/appstore/list",
      api_class: "AppStoreApi",
      generated_method: :app_store_list,
      parameters: [
        { name: :collection, wire_name: "collection", location: :query, required: false },
        { name: :category, wire_name: "category", location: :query, required: false },
        { name: :country, wire_name: "country", location: :query, required: false },
        { name: :lang, wire_name: "lang", location: :query, required: false },
        { name: :num, wire_name: "num", location: :query, required: false },
        { name: :full_detail, wire_name: "fullDetail", location: :query, required: false },
      ].freeze
    }.freeze,
    app_store_privacy: {
      operation_id: "appStorePrivacy",
      path: "/v1/appstore/privacy",
      api_class: "AppStoreApi",
      generated_method: :app_store_privacy,
      parameters: [
        { name: :id, wire_name: "id", location: :query, required: true },
      ].freeze
    }.freeze,
    app_store_ratings: {
      operation_id: "appStoreRatings",
      path: "/v1/appstore/ratings",
      api_class: "AppStoreApi",
      generated_method: :app_store_ratings,
      parameters: [
        { name: :id, wire_name: "id", location: :query, required: false },
        { name: :country, wire_name: "country", location: :query, required: false },
        { name: :app_id, wire_name: "appId", location: :query, required: false },
      ].freeze
    }.freeze,
    app_store_reviews: {
      operation_id: "appStoreReviews",
      path: "/v1/appstore/reviews",
      api_class: "AppStoreApi",
      generated_method: :app_store_reviews,
      parameters: [
        { name: :id, wire_name: "id", location: :query, required: false },
        { name: :app_id, wire_name: "appId", location: :query, required: false },
        { name: :country, wire_name: "country", location: :query, required: false },
        { name: :page, wire_name: "page", location: :query, required: false },
        { name: :sort, wire_name: "sort", location: :query, required: false },
      ].freeze
    }.freeze,
    app_store_search: {
      operation_id: "appStoreSearch",
      path: "/v1/appstore/search",
      api_class: "AppStoreApi",
      generated_method: :app_store_search,
      parameters: [
        { name: :term, wire_name: "term", location: :query, required: true },
        { name: :num, wire_name: "num", location: :query, required: false },
        { name: :page, wire_name: "page", location: :query, required: false },
        { name: :country, wire_name: "country", location: :query, required: false },
        { name: :lang, wire_name: "lang", location: :query, required: false },
        { name: :ids_only, wire_name: "idsOnly", location: :query, required: false },
      ].freeze
    }.freeze,
    app_store_similar: {
      operation_id: "appStoreSimilar",
      path: "/v1/appstore/similar",
      api_class: "AppStoreApi",
      generated_method: :app_store_similar,
      parameters: [
        { name: :id, wire_name: "id", location: :query, required: false },
        { name: :app_id, wire_name: "appId", location: :query, required: false },
      ].freeze
    }.freeze,
    app_store_suggest: {
      operation_id: "appStoreSuggest",
      path: "/v1/appstore/suggest",
      api_class: "AppStoreApi",
      generated_method: :app_store_suggest,
      parameters: [
        { name: :term, wire_name: "term", location: :query, required: true },
      ].freeze
    }.freeze,
    brand_fonts: {
      operation_id: "brandFonts",
      path: "/v1/brand/fonts",
      api_class: "BrandApi",
      generated_method: :brand_fonts,
      parameters: [
        { name: :domain, wire_name: "domain", location: :query, required: false },
        { name: :url, wire_name: "url", location: :query, required: false },
      ].freeze
    }.freeze,
    brand_retrieve: {
      operation_id: "brandRetrieve",
      path: "/v1/brand/retrieve",
      api_class: "BrandApi",
      generated_method: :brand_retrieve,
      parameters: [
        { name: :domain, wire_name: "domain", location: :query, required: false },
        { name: :url, wire_name: "url", location: :query, required: false },
      ].freeze
    }.freeze,
    brand_search: {
      operation_id: "brandSearch",
      path: "/v1/brand/search",
      api_class: "BrandApi",
      generated_method: :brand_search,
      parameters: [
        { name: :query, wire_name: "query", location: :query, required: true },
        { name: :limit, wire_name: "limit", location: :query, required: false },
      ].freeze
    }.freeze,
    brand_styleguide: {
      operation_id: "brandStyleguide",
      path: "/v1/brand/styleguide",
      api_class: "BrandApi",
      generated_method: :brand_styleguide,
      parameters: [
        { name: :domain, wire_name: "domain", location: :query, required: false },
        { name: :url, wire_name: "url", location: :query, required: false },
      ].freeze
    }.freeze,
    fomo_alerts: {
      operation_id: "fomoAlerts",
      path: "/v1/fomo/alerts",
      api_class: "FomoApi",
      generated_method: :fomo_alerts,
      parameters: [
        { name: :type, wire_name: "type", location: :query, required: false },
        { name: :chain, wire_name: "chain", location: :query, required: false },
        { name: :since, wire_name: "since", location: :query, required: false },
        { name: :limit, wire_name: "limit", location: :query, required: false },
      ].freeze
    }.freeze,
    fomo_leaderboard: {
      operation_id: "fomoLeaderboard",
      path: "/v1/fomo/leaderboard/{window}",
      api_class: "FomoApi",
      generated_method: :fomo_leaderboard,
      parameters: [
        { name: :window, wire_name: "window", location: :path, required: true },
        { name: :chain, wire_name: "chain", location: :query, required: false },
        { name: :limit, wire_name: "limit", location: :query, required: false },
      ].freeze
    }.freeze,
    fomo_notifications: {
      operation_id: "fomoNotifications",
      path: "/v1/fomo/notifications",
      api_class: "FomoApi",
      generated_method: :fomo_notifications,
      parameters: [
        { name: :type, wire_name: "type", location: :query, required: false },
        { name: :chain, wire_name: "chain", location: :query, required: false },
        { name: :since, wire_name: "since", location: :query, required: false },
        { name: :limit, wire_name: "limit", location: :query, required: false },
      ].freeze
    }.freeze,
    fomo_search: {
      operation_id: "fomoSearch",
      path: "/v1/fomo/search",
      api_class: "FomoApi",
      generated_method: :fomo_search,
      parameters: [
        { name: :q, wire_name: "q", location: :query, required: true },
        { name: :type, wire_name: "type", location: :query, required: false },
        { name: :chain, wire_name: "chain", location: :query, required: false },
        { name: :limit, wire_name: "limit", location: :query, required: false },
      ].freeze
    }.freeze,
    fomo_thesis: {
      operation_id: "fomoThesis",
      path: "/v1/fomo/thesis",
      api_class: "FomoApi",
      generated_method: :fomo_thesis,
      parameters: [
        { name: :chain, wire_name: "chain", location: :query, required: false },
        { name: :limit, wire_name: "limit", location: :query, required: false },
      ].freeze
    }.freeze,
    fomo_thesis_by_token: {
      operation_id: "fomoThesisByToken",
      path: "/v1/fomo/thesis/token/{mint}",
      api_class: "FomoApi",
      generated_method: :fomo_thesis_by_token,
      parameters: [
        { name: :mint, wire_name: "mint", location: :path, required: true },
        { name: :network, wire_name: "network", location: :query, required: false },
        { name: :limit, wire_name: "limit", location: :query, required: false },
      ].freeze
    }.freeze,
    fomo_thesis_by_user: {
      operation_id: "fomoThesisByUser",
      path: "/v1/fomo/thesis/user/{id}",
      api_class: "FomoApi",
      generated_method: :fomo_thesis_by_user,
      parameters: [
        { name: :id, wire_name: "id", location: :path, required: true },
        { name: :chain, wire_name: "chain", location: :query, required: false },
        { name: :sort, wire_name: "sort", location: :query, required: false },
        { name: :limit, wire_name: "limit", location: :query, required: false },
      ].freeze
    }.freeze,
    fomo_thesis_by_user_token: {
      operation_id: "fomoThesisByUserToken",
      path: "/v1/fomo/thesis/user/{id}/token/{address}",
      api_class: "FomoApi",
      generated_method: :fomo_thesis_by_user_token,
      parameters: [
        { name: :id, wire_name: "id", location: :path, required: true },
        { name: :address, wire_name: "address", location: :path, required: true },
        { name: :limit, wire_name: "limit", location: :query, required: false },
      ].freeze
    }.freeze,
    fomo_token_holders: {
      operation_id: "fomoTokenHolders",
      path: "/v1/fomo/tokens/{address}/holders",
      api_class: "FomoApi",
      generated_method: :fomo_token_holders,
      parameters: [
        { name: :address, wire_name: "address", location: :path, required: true },
        { name: :limit, wire_name: "limit", location: :query, required: false },
      ].freeze
    }.freeze,
    fomo_tokens_graduated: {
      operation_id: "fomoTokensGraduated",
      path: "/v1/fomo/tokens/graduated",
      api_class: "FomoApi",
      generated_method: :fomo_tokens_graduated,
      parameters: [
        { name: :chain, wire_name: "chain", location: :query, required: false },
        { name: :limit, wire_name: "limit", location: :query, required: false },
      ].freeze
    }.freeze,
    fomo_tokens_most_held: {
      operation_id: "fomoTokensMostHeld",
      path: "/v1/fomo/tokens/most-held",
      api_class: "FomoApi",
      generated_method: :fomo_tokens_most_held,
      parameters: [
        { name: :chain, wire_name: "chain", location: :query, required: false },
        { name: :limit, wire_name: "limit", location: :query, required: false },
      ].freeze
    }.freeze,
    fomo_tokens_trending: {
      operation_id: "fomoTokensTrending",
      path: "/v1/fomo/tokens/trending",
      api_class: "FomoApi",
      generated_method: :fomo_tokens_trending,
      parameters: [
        { name: :chain, wire_name: "chain", location: :query, required: false },
        { name: :limit, wire_name: "limit", location: :query, required: false },
      ].freeze
    }.freeze,
    fomo_trade: {
      operation_id: "fomoTrade",
      path: "/v1/fomo/trades/{trade_id}",
      api_class: "FomoApi",
      generated_method: :fomo_trade,
      parameters: [
        { name: :trade_id, wire_name: "trade_id", location: :path, required: true },
      ].freeze
    }.freeze,
    fomo_user_balances: {
      operation_id: "fomoUserBalances",
      path: "/v1/fomo/users/{handle}/balances",
      api_class: "FomoApi",
      generated_method: :fomo_user_balances,
      parameters: [
        { name: :handle, wire_name: "handle", location: :path, required: true },
      ].freeze
    }.freeze,
    fomo_user_profile: {
      operation_id: "fomoUserProfile",
      path: "/v1/fomo/users/{handle}",
      api_class: "FomoApi",
      generated_method: :fomo_user_profile,
      parameters: [
        { name: :handle, wire_name: "handle", location: :path, required: true },
      ].freeze
    }.freeze,
    fomo_user_trades: {
      operation_id: "fomoUserTrades",
      path: "/v1/fomo/users/{handle}/trades",
      api_class: "FomoApi",
      generated_method: :fomo_user_trades,
      parameters: [
        { name: :handle, wire_name: "handle", location: :path, required: true },
        { name: :limit, wire_name: "limit", location: :query, required: false },
      ].freeze
    }.freeze,
    google_maps_place_details: {
      operation_id: "googleMapsPlaceDetails",
      path: "/v1/googlemaps/details/{place_id}",
      api_class: "GoogleMapsApi",
      generated_method: :google_maps_place_details,
      parameters: [
        { name: :place_id, wire_name: "place_id", location: :path, required: true },
      ].freeze
    }.freeze,
    google_maps_place_reviews: {
      operation_id: "googleMapsPlaceReviews",
      path: "/v1/googlemaps/reviews/{place_id}",
      api_class: "GoogleMapsApi",
      generated_method: :google_maps_place_reviews,
      parameters: [
        { name: :place_id, wire_name: "place_id", location: :path, required: true },
        { name: :limit, wire_name: "limit", location: :query, required: false },
      ].freeze
    }.freeze,
    google_maps_search_places: {
      operation_id: "googleMapsSearchPlaces",
      path: "/v1/googlemaps/search",
      api_class: "GoogleMapsApi",
      generated_method: :google_maps_search_places,
      parameters: [
        { name: :query, wire_name: "query", location: :query, required: true },
        { name: :lat, wire_name: "lat", location: :query, required: false },
        { name: :lng, wire_name: "lng", location: :query, required: false },
        { name: :radius, wire_name: "radius", location: :query, required: false },
      ].freeze
    }.freeze,
    google_play_app_details: {
      operation_id: "googlePlayAppDetails",
      path: "/v1/googleplay/app_details/{id}",
      api_class: "GooglePlayApi",
      generated_method: :google_play_app_details,
      parameters: [
        { name: :id, wire_name: "id", location: :path, required: true },
        { name: :country, wire_name: "country", location: :query, required: false },
        { name: :language, wire_name: "language", location: :query, required: false },
      ].freeze
    }.freeze,
    google_play_availability: {
      operation_id: "googlePlayAvailability",
      path: "/v1/googleplay/availability/{id}",
      api_class: "GooglePlayApi",
      generated_method: :google_play_availability,
      parameters: [
        { name: :id, wire_name: "id", location: :path, required: true },
        { name: :country, wire_name: "country", location: :query, required: false },
        { name: :countries, wire_name: "countries", location: :query, required: false },
        { name: :language, wire_name: "language", location: :query, required: false },
      ].freeze
    }.freeze,
    google_play_categories: {
      operation_id: "googlePlayCategories",
      path: "/v1/googleplay/categories",
      api_class: "GooglePlayApi",
      generated_method: :google_play_categories,
      parameters: [
        { name: :country, wire_name: "country", location: :query, required: false },
        { name: :language, wire_name: "language", location: :query, required: false },
      ].freeze
    }.freeze,
    google_play_category_apps: {
      operation_id: "googlePlayCategoryApps",
      path: "/v1/googleplay/category_apps/{category}",
      api_class: "GooglePlayApi",
      generated_method: :google_play_category_apps,
      parameters: [
        { name: :category, wire_name: "category", location: :path, required: true },
        { name: :country, wire_name: "country", location: :query, required: false },
        { name: :language, wire_name: "language", location: :query, required: false },
        { name: :limit, wire_name: "limit", location: :query, required: false },
      ].freeze
    }.freeze,
    google_play_data_safety: {
      operation_id: "googlePlayDataSafety",
      path: "/v1/googleplay/data_safety/{id}",
      api_class: "GooglePlayApi",
      generated_method: :google_play_data_safety,
      parameters: [
        { name: :id, wire_name: "id", location: :path, required: true },
        { name: :country, wire_name: "country", location: :query, required: false },
        { name: :language, wire_name: "language", location: :query, required: false },
      ].freeze
    }.freeze,
    google_play_developer: {
      operation_id: "googlePlayDeveloper",
      path: "/v1/googleplay/developer",
      api_class: "GooglePlayApi",
      generated_method: :google_play_developer,
      parameters: [
        { name: :dev_id, wire_name: "dev_id", location: :query, required: true },
        { name: :country, wire_name: "country", location: :query, required: false },
        { name: :language, wire_name: "language", location: :query, required: false },
        { name: :limit, wire_name: "limit", location: :query, required: false },
      ].freeze
    }.freeze,
    google_play_permissions: {
      operation_id: "googlePlayPermissions",
      path: "/v1/googleplay/permissions/{id}",
      api_class: "GooglePlayApi",
      generated_method: :google_play_permissions,
      parameters: [
        { name: :id, wire_name: "id", location: :path, required: true },
        { name: :country, wire_name: "country", location: :query, required: false },
        { name: :language, wire_name: "language", location: :query, required: false },
      ].freeze
    }.freeze,
    google_play_reviews: {
      operation_id: "googlePlayReviews",
      path: "/v1/googleplay/reviews/{id}",
      api_class: "GooglePlayApi",
      generated_method: :google_play_reviews,
      parameters: [
        { name: :id, wire_name: "id", location: :path, required: true },
        { name: :country, wire_name: "country", location: :query, required: false },
        { name: :language, wire_name: "language", location: :query, required: false },
        { name: :limit, wire_name: "limit", location: :query, required: false },
        { name: :sort, wire_name: "sort", location: :query, required: false },
        { name: :score, wire_name: "score", location: :query, required: false },
        { name: :next_token, wire_name: "next_token", location: :query, required: false },
      ].freeze
    }.freeze,
    google_play_search: {
      operation_id: "googlePlaySearch",
      path: "/v1/googleplay/search",
      api_class: "GooglePlayApi",
      generated_method: :google_play_search,
      parameters: [
        { name: :term, wire_name: "term", location: :query, required: true },
        { name: :country, wire_name: "country", location: :query, required: false },
        { name: :language, wire_name: "language", location: :query, required: false },
        { name: :limit, wire_name: "limit", location: :query, required: false },
      ].freeze
    }.freeze,
    google_play_similar_apps: {
      operation_id: "googlePlaySimilarApps",
      path: "/v1/googleplay/similar_apps/{id}",
      api_class: "GooglePlayApi",
      generated_method: :google_play_similar_apps,
      parameters: [
        { name: :id, wire_name: "id", location: :path, required: true },
        { name: :country, wire_name: "country", location: :query, required: false },
        { name: :language, wire_name: "language", location: :query, required: false },
        { name: :limit, wire_name: "limit", location: :query, required: false },
      ].freeze
    }.freeze,
    google_play_suggest: {
      operation_id: "googlePlaySuggest",
      path: "/v1/googleplay/suggest",
      api_class: "GooglePlayApi",
      generated_method: :google_play_suggest,
      parameters: [
        { name: :term, wire_name: "term", location: :query, required: true },
        { name: :country, wire_name: "country", location: :query, required: false },
        { name: :language, wire_name: "language", location: :query, required: false },
        { name: :limit, wire_name: "limit", location: :query, required: false },
      ].freeze
    }.freeze,
    google_search: {
      operation_id: "googleSearch",
      path: "/v1/web/search",
      api_class: "GoogleApi",
      generated_method: :google_search,
      parameters: [
        { name: :text, wire_name: "text", location: :query, required: true },
        { name: :engines, wire_name: "engines", location: :query, required: false },
        { name: :lang, wire_name: "lang", location: :query, required: false },
        { name: :region, wire_name: "region", location: :query, required: false },
        { name: :date, wire_name: "date", location: :query, required: false },
        { name: :site, wire_name: "site", location: :query, required: false },
        { name: :limit, wire_name: "limit", location: :query, required: false },
        { name: :start, wire_name: "start", location: :query, required: false },
        { name: :cursor, wire_name: "cursor", location: :query, required: false },
      ].freeze
    }.freeze,
    google_shopping_product_offers: {
      operation_id: "googleShoppingProductOffers",
      path: "/v1/googleshopping/product_offers",
      api_class: "GoogleShoppingApi",
      generated_method: :google_shopping_product_offers,
      parameters: [
        { name: :product_id, wire_name: "product_id", location: :query, required: false },
        { name: :text, wire_name: "text", location: :query, required: true },
        { name: :lang, wire_name: "lang", location: :query, required: false },
        { name: :country, wire_name: "country", location: :query, required: false },
        { name: :domain, wire_name: "domain", location: :query, required: false },
        { name: :limit, wire_name: "limit", location: :query, required: false },
      ].freeze
    }.freeze,
    google_shopping_search: {
      operation_id: "googleShoppingSearch",
      path: "/v1/googleshopping/search",
      api_class: "GoogleShoppingApi",
      generated_method: :google_shopping_search,
      parameters: [
        { name: :text, wire_name: "text", location: :query, required: true },
        { name: :lang, wire_name: "lang", location: :query, required: false },
        { name: :country, wire_name: "country", location: :query, required: false },
        { name: :domain, wire_name: "domain", location: :query, required: false },
        { name: :limit, wire_name: "limit", location: :query, required: false },
        { name: :start, wire_name: "start", location: :query, required: false },
      ].freeze
    }.freeze,
    hacker_news_item: {
      operation_id: "hackerNewsItem",
      path: "/v1/hackernews/item/{id}",
      api_class: "HackerNewsApi",
      generated_method: :hacker_news_item,
      parameters: [
        { name: :id, wire_name: "id", location: :path, required: true },
        { name: :depth, wire_name: "depth", location: :query, required: false },
      ].freeze
    }.freeze,
    hacker_news_search: {
      operation_id: "hackerNewsSearch",
      path: "/v1/hackernews/search",
      api_class: "HackerNewsApi",
      generated_method: :hacker_news_search,
      parameters: [
        { name: :q, wire_name: "q", location: :query, required: true },
        { name: :tags, wire_name: "tags", location: :query, required: false },
        { name: :limit, wire_name: "limit", location: :query, required: false },
        { name: :page, wire_name: "page", location: :query, required: false },
      ].freeze
    }.freeze,
    hacker_news_stories_ask: {
      operation_id: "hackerNewsStoriesAsk",
      path: "/v1/hackernews/stories_ask",
      api_class: "HackerNewsApi",
      generated_method: :hacker_news_stories_ask,
      parameters: [
        { name: :limit, wire_name: "limit", location: :query, required: false },
        { name: :page, wire_name: "page", location: :query, required: false },
      ].freeze
    }.freeze,
    hacker_news_stories_best: {
      operation_id: "hackerNewsStoriesBest",
      path: "/v1/hackernews/stories_best",
      api_class: "HackerNewsApi",
      generated_method: :hacker_news_stories_best,
      parameters: [
        { name: :limit, wire_name: "limit", location: :query, required: false },
        { name: :page, wire_name: "page", location: :query, required: false },
      ].freeze
    }.freeze,
    hacker_news_stories_job: {
      operation_id: "hackerNewsStoriesJob",
      path: "/v1/hackernews/stories_job",
      api_class: "HackerNewsApi",
      generated_method: :hacker_news_stories_job,
      parameters: [
        { name: :limit, wire_name: "limit", location: :query, required: false },
        { name: :page, wire_name: "page", location: :query, required: false },
      ].freeze
    }.freeze,
    hacker_news_stories_new: {
      operation_id: "hackerNewsStoriesNew",
      path: "/v1/hackernews/stories_new",
      api_class: "HackerNewsApi",
      generated_method: :hacker_news_stories_new,
      parameters: [
        { name: :limit, wire_name: "limit", location: :query, required: false },
        { name: :page, wire_name: "page", location: :query, required: false },
      ].freeze
    }.freeze,
    hacker_news_stories_show: {
      operation_id: "hackerNewsStoriesShow",
      path: "/v1/hackernews/stories_show",
      api_class: "HackerNewsApi",
      generated_method: :hacker_news_stories_show,
      parameters: [
        { name: :limit, wire_name: "limit", location: :query, required: false },
        { name: :page, wire_name: "page", location: :query, required: false },
      ].freeze
    }.freeze,
    hacker_news_stories_top: {
      operation_id: "hackerNewsStoriesTop",
      path: "/v1/hackernews/stories_top",
      api_class: "HackerNewsApi",
      generated_method: :hacker_news_stories_top,
      parameters: [
        { name: :limit, wire_name: "limit", location: :query, required: false },
        { name: :page, wire_name: "page", location: :query, required: false },
      ].freeze
    }.freeze,
    hacker_news_user: {
      operation_id: "hackerNewsUser",
      path: "/v1/hackernews/user/{handle}",
      api_class: "HackerNewsApi",
      generated_method: :hacker_news_user,
      parameters: [
        { name: :handle, wire_name: "handle", location: :path, required: true },
      ].freeze
    }.freeze,
    instagram_posts: {
      operation_id: "instagramPosts",
      path: "/v1/instagram/posts",
      api_class: "InstagramApi",
      generated_method: :instagram_posts,
      parameters: [
        { name: :username, wire_name: "username", location: :query, required: false },
        { name: :limit, wire_name: "limit", location: :query, required: false },
        { name: :cursor, wire_name: "cursor", location: :query, required: false },
      ].freeze
    }.freeze,
    instagram_profile: {
      operation_id: "instagramProfile",
      path: "/v1/instagram/profile",
      api_class: "InstagramApi",
      generated_method: :instagram_profile,
      parameters: [
        { name: :username, wire_name: "username", location: :query, required: false },
      ].freeze
    }.freeze,
    reddit_post_by_id: {
      operation_id: "redditPostById",
      path: "/v1/reddit/post_by_id/{id}",
      api_class: "RedditApi",
      generated_method: :reddit_post_by_id,
      parameters: [
        { name: :id, wire_name: "id", location: :path, required: true },
        { name: :context, wire_name: "context", location: :query, required: false },
      ].freeze
    }.freeze,
    reddit_post_by_permalink: {
      operation_id: "redditPostByPermalink",
      path: "/v1/reddit/post_by_permalink",
      api_class: "RedditApi",
      generated_method: :reddit_post_by_permalink,
      parameters: [
        { name: :permalink, wire_name: "permalink", location: :query, required: false },
        { name: :context, wire_name: "context", location: :query, required: false },
      ].freeze
    }.freeze,
    reddit_search: {
      operation_id: "redditSearch",
      path: "/v1/reddit/search_posts",
      api_class: "RedditApi",
      generated_method: :reddit_search,
      parameters: [
        { name: :query, wire_name: "query", location: :query, required: true },
        { name: :sort, wire_name: "sort", location: :query, required: false },
        { name: :limit, wire_name: "limit", location: :query, required: false },
        { name: :time_filter, wire_name: "time_filter", location: :query, required: false },
      ].freeze
    }.freeze,
    reddit_subreddit_posts: {
      operation_id: "redditSubredditPosts",
      path: "/v1/reddit/subreddit_posts/{subreddit}",
      api_class: "RedditApi",
      generated_method: :reddit_subreddit_posts,
      parameters: [
        { name: :subreddit, wire_name: "subreddit", location: :path, required: true },
        { name: :category, wire_name: "category", location: :query, required: false },
        { name: :time_filter, wire_name: "time_filter", location: :query, required: false },
        { name: :sort, wire_name: "sort", location: :query, required: false },
        { name: :limit, wire_name: "limit", location: :query, required: false },
      ].freeze
    }.freeze,
    reddit_user_activity: {
      operation_id: "redditUserActivity",
      path: "/v1/reddit/user_activity/{username}",
      api_class: "RedditApi",
      generated_method: :reddit_user_activity,
      parameters: [
        { name: :username, wire_name: "username", location: :path, required: true },
        { name: :limit, wire_name: "limit", location: :query, required: false },
        { name: :sort, wire_name: "sort", location: :query, required: false },
      ].freeze
    }.freeze,
    reddit_user_posts: {
      operation_id: "redditUserPosts",
      path: "/v1/reddit/user_posts/{username}",
      api_class: "RedditApi",
      generated_method: :reddit_user_posts,
      parameters: [
        { name: :username, wire_name: "username", location: :path, required: true },
        { name: :category, wire_name: "category", location: :query, required: false },
        { name: :time_filter, wire_name: "time_filter", location: :query, required: false },
        { name: :sort, wire_name: "sort", location: :query, required: false },
        { name: :limit, wire_name: "limit", location: :query, required: false },
      ].freeze
    }.freeze,
    tiktok_post: {
      operation_id: "tiktokPost",
      path: "/v1/tiktok/post/{id}",
      api_class: "TiktokApi",
      generated_method: :tiktok_post,
      parameters: [
        { name: :id, wire_name: "id", location: :path, required: true },
      ].freeze
    }.freeze,
    tiktok_user: {
      operation_id: "tiktokUser",
      path: "/v1/tiktok/user/{handle}",
      api_class: "TiktokApi",
      generated_method: :tiktok_user,
      parameters: [
        { name: :handle, wire_name: "handle", location: :path, required: true },
      ].freeze
    }.freeze,
    tiktok_user_posts: {
      operation_id: "tiktokUserPosts",
      path: "/v1/tiktok/user_posts/{handle}",
      api_class: "TiktokApi",
      generated_method: :tiktok_user_posts,
      parameters: [
        { name: :handle, wire_name: "handle", location: :path, required: true },
        { name: :count, wire_name: "count", location: :query, required: false },
        { name: :cursor, wire_name: "cursor", location: :query, required: false },
      ].freeze
    }.freeze,
    web_brand: {
      operation_id: "webBrand",
      path: "/v1/webcontext/brand",
      api_class: "WebApi",
      generated_method: :web_brand,
      parameters: [
        { name: :url, wire_name: "url", location: :query, required: true },
      ].freeze
    }.freeze,
    web_crawl: {
      operation_id: "webCrawl",
      path: "/v1/webcontext/crawl",
      api_class: "WebApi",
      generated_method: :web_crawl,
      parameters: [
        { name: :url, wire_name: "url", location: :query, required: true },
        { name: :max_pages, wire_name: "max_pages", location: :query, required: false },
        { name: :max_depth, wire_name: "max_depth", location: :query, required: false },
      ].freeze
    }.freeze,
    web_map: {
      operation_id: "webMap",
      path: "/v1/webcontext/map",
      api_class: "WebApi",
      generated_method: :web_map,
      parameters: [
        { name: :url, wire_name: "url", location: :query, required: true },
      ].freeze
    }.freeze,
    web_scrape: {
      operation_id: "webScrape",
      path: "/v1/webcontext/scrape",
      api_class: "WebApi",
      generated_method: :web_scrape,
      parameters: [
        { name: :url, wire_name: "url", location: :query, required: true },
        { name: :include_selectors, wire_name: "include_selectors", location: :query, required: false },
        { name: :exclude_selectors, wire_name: "exclude_selectors", location: :query, required: false },
      ].freeze
    }.freeze,
    youtube_channel: {
      operation_id: "youtubeChannel",
      path: "/v1/youtube/channel/{id}",
      api_class: "YoutubeApi",
      generated_method: :youtube_channel,
      parameters: [
        { name: :id, wire_name: "id", location: :path, required: true },
        { name: :language, wire_name: "language", location: :query, required: false },
      ].freeze
    }.freeze,
    youtube_comments: {
      operation_id: "youtubeComments",
      path: "/v1/youtube/comments/{id}",
      api_class: "YoutubeApi",
      generated_method: :youtube_comments,
      parameters: [
        { name: :id, wire_name: "id", location: :path, required: true },
        { name: :limit, wire_name: "limit", location: :query, required: false },
      ].freeze
    }.freeze,
    youtube_playlist: {
      operation_id: "youtubePlaylist",
      path: "/v1/youtube/playlist/{id}",
      api_class: "YoutubeApi",
      generated_method: :youtube_playlist,
      parameters: [
        { name: :id, wire_name: "id", location: :path, required: true },
        { name: :language, wire_name: "language", location: :query, required: false },
      ].freeze
    }.freeze,
    youtube_related: {
      operation_id: "youtubeRelated",
      path: "/v1/youtube/related/{id}",
      api_class: "YoutubeApi",
      generated_method: :youtube_related,
      parameters: [
        { name: :id, wire_name: "id", location: :path, required: true },
        { name: :language, wire_name: "language", location: :query, required: false },
      ].freeze
    }.freeze,
    youtube_search: {
      operation_id: "youtubeSearch",
      path: "/v1/youtube/search",
      api_class: "YoutubeApi",
      generated_method: :youtube_search,
      parameters: [
        { name: :term, wire_name: "term", location: :query, required: true },
        { name: :language, wire_name: "language", location: :query, required: false },
        { name: :limit, wire_name: "limit", location: :query, required: false },
      ].freeze
    }.freeze,
    youtube_transcript: {
      operation_id: "youtubeTranscript",
      path: "/v1/youtube/transcript/{id}",
      api_class: "YoutubeApi",
      generated_method: :youtube_transcript,
      parameters: [
        { name: :id, wire_name: "id", location: :path, required: true },
        { name: :language, wire_name: "language", location: :query, required: false },
      ].freeze
    }.freeze,
    youtube_video: {
      operation_id: "youtubeVideo",
      path: "/v1/youtube/video/{id}",
      api_class: "YoutubeApi",
      generated_method: :youtube_video,
      parameters: [
        { name: :id, wire_name: "id", location: :path, required: true },
        { name: :language, wire_name: "language", location: :query, required: false },
      ].freeze
    }.freeze,
  }.freeze
  ALIASES = {}.freeze
end
